[profile.default]
src = 'contracts'
out = 'artifacts'
test = 'test-sol'
libs = ['node_modules', 'lib']
solc = '0.8.24'
optimizer = true
evm_version = 'cancun'
optimizer_runs = 10000
gas_reports = ['*']
remappings = [
    'hardhat/=node_modules/hardhat/',
    'ds-test/=lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
]
fs_permissions = [{ access = 'read', path = './test-sol/config/' }]


# Formatting -> https://getfoundry.sh/config/reference/formatter/
[fmt]
bracket_spacing = true
number_underscore = "thousands"
# line_length = 120
# tab_width = 4


# Linting -> https://getfoundry.sh/config/reference/linter
[lint]
# TODO -> Will remove as much of those and fix them in later commits
exclude_lints = [
    # "unaliased-plain-import",
    "unused-import",
    "asm-keccak256",
    # "incorrect-shift",
    "unchecked-call",
    "erc20-unchecked-transfer",

    "mixed-case-function",
    "mixed-case-variable",
    "screaming-snake-case-const",
    "screaming-snake-case-immutable",
    "pascal-case-struct",
]

# https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
